name=SmokeDisplays
version=1.0.1
author=DURUCZ Béla <thembeddevguy@gmail.com>
maintainer=DURUCZ Béla <thembeddevguy@gmail.com>
sentence=Arduino library to drive salvaged displays from "disposable" vapes.
paragraph=Driver for different displays.
category=Display
url=https://github.com/the-developer-guy/SmokeDisplays
architectures=*
includes=SmokeDisplay.h
